"""The frozen `gt.csv` column spec, its validator, and its loader (Phase 10a). 🟢 PHI-FREE.

`gt.csv` is the yardstick every engine is scored against: it is frozen and hashed, so its
shape is a correctness property, not a formatting preference (CLAUDE.md rule #8). This
module is the ONE place that defines that shape. It contains no pixel access, no DICOM, no
network, and no token inspection — it moves strings between a CSV and `GTToken` and checks
their form.

D-2.3: the `GTToken` dataclass stays in `harness/contract.py` (so `matching.py` and
`metrics.py` can import the GT shape without depending on this PHI-touching package); the
CSV spec and its validation live only here.

Columns, in this exact order — the `GTToken` fields with `bbox` flattened to four:

    image_id, series_uid, modality, vendor, stratum, frame_idx, token_text, x0, y0, x1, y1, label

--------------------------------------------------------------------------------------
WHY EVERY ERROR STRING IS PHI-FREE BY CONSTRUCTION
--------------------------------------------------------------------------------------
A human runs this validator against the real `gt.csv` and may paste its output back to
Claude, so a violation must never carry a field VALUE. `GTError` therefore has no free-text
field at all: it holds a row index, a column NAME, and a code, and its human-readable
`detail` is looked up from the fixed `_CODE_DETAIL` table. There is no code path that can
interpolate a cell into a message.

That is stricter than "don't echo `token_text`", and deliberately so. In a malformed row the
values are in the WRONG columns — a quoting error can put the patient ID under `x0` — so
"echo the offending coordinate, it's only a number" is not safe either. No values, ever.

This module also never `print()`s: `validate_gt()` returns a report object and the caller
decides what to do with it.

--------------------------------------------------------------------------------------
RESOLVED DECISIONS (2026-08-05)
--------------------------------------------------------------------------------------
1. Packaging: `ground_truth/` is a real package (`__init__.py` + `ground_truth*` in
   pyproject's `packages.find`) so this module has one import form everywhere.
2. `image_sizes` is REQUIRED, not optional. The in-bounds check is not skippable: a
   validation report that silently omitted it would read as "boxes verified" when nothing
   was checked. The caller feeds it 10b's PHI-free render manifest — `(image_id, frame_idx,
   w, h, sha256)` — of which only `image_id -> (w, h)` is needed here.
3. This module exposes a LOADER, not just a validator, returning exactly
   `dict[str, list[GTToken]]` — the shape `harness/harness.py:99` takes. One CSV->GTToken
   parser in the codebase means one place where the four bbox columns can be reassembled in
   the wrong order.
4. `PHI`/`KEEP` are IMPORTED from `harness.metrics`, not redefined here. A local copy could
   drift out of sync with the scorer's vocabulary; an import cannot.
5. `validate_gt()` COLLECTS every violation (a human running this once over the whole GT
   wants the full list, not one error per round trip). `load_gt()` RAISES on any violation,
   so no programmatic caller can score against a broken file. The header must match
   `COLUMNS` exactly, INCLUDING order — a reordered header means `gt.csv` was regenerated by
   a different path, which is exactly the silent change rule #8 exists to surface.
7. Reading uses the stdlib `csv` module, not pandas. `pandas.read_csv` NA-filters even with
   `dtype=str`, so a `token_text` of literally "NA" or "NULL" would come back as `NaN` —
   silent corruption of the one artifact whose byte-identity everything rests on. Pandas
   also renames duplicate headers (`x0`, `x0.1`), hiding the very error we want reported.

(6 needed no decision — see "WHAT THIS VALIDATOR CANNOT CHECK" below.)

--------------------------------------------------------------------------------------
WHAT THIS VALIDATOR CANNOT CHECK — DO NOT ADD IT LATER
--------------------------------------------------------------------------------------
Confirmed-blank `ct_axial` negative-control frames contribute ZERO rows to `gt.csv`. An
image with no burned-in text is simply ABSENT from the file, so:

  * a header-only `gt.csv` is VALID, and
  * from inside the CSV, "this image was reviewed and found blank" and "this image was never
    reviewed" are indistinguishable.

Therefore this module is row-local and header-level only. It CANNOT check set membership or
completeness against the manifest, and nobody should add a "every manifest image must
appear" rule here — that would make the negative-control set unrepresentable. Coverage is
checked in 10e, against the reviewed-image set and the manifest.

Likewise, `modality`/`vendor`/`stratum` are allowed to be empty. They are manifest
pass-throughs carried for readability; `run_harness` stamps the authoritative values onto
every score row from `ImageRef` (CLAUDE.md rule #7), so a blank one here cannot corrupt a
metric. A missing DICOM `Manufacturer` is a data-quality question for 10e, not a schema
violation. `image_id`, `series_uid`, and `token_text` must be non-empty: the first is the
dict key, the last is the yardstick itself.

--------------------------------------------------------------------------------------
`normalize()` IS NOT APPLIED HERE
--------------------------------------------------------------------------------------
`token_text` is stored and returned RAW — no stripping, no case folding, no NFC. The frozen
`normalize()` (`harness/contract.py:121-139`) is applied at MATCH time, to both sides, and
only there. Normalizing on the way out of the CSV would normalize the ground truth twice and
quietly shift the yardstick. This module does not import it.
"""

from __future__ import annotations

import csv
import math
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path

from harness.contract import GTToken
from harness.metrics import KEEP, PHI

# --- the frozen spec -------------------------------------------------------------------

# The four columns `GTToken.bbox` flattens into, in corner order (x0, y0, x1, y1).
BBOX_COLUMNS: tuple[str, ...] = ("x0", "y0", "x1", "y1")

# Written out as a literal, NOT derived from `dataclasses.fields(GTToken)` at import time:
# a frozen artifact's spec must be explicit, so that adding a field to `GTToken` FAILS a test
# instead of silently changing what `gt.csv` is supposed to look like. `tests/test_gt_schema.py`
# asserts this tuple is derivable from the dataclass, with `bbox` expanded to `BBOX_COLUMNS`.
COLUMNS: tuple[str, ...] = (
    "image_id",
    "series_uid",
    "modality",
    "vendor",
    "stratum",
    "frame_idx",
    "token_text",
    "x0",
    "y0",
    "x1",
    "y1",
    "label",
)

# Binary and case-sensitive. There is no OTHER: the label vocabulary is exactly these two.
ALLOWED_LABELS: frozenset[str] = frozenset({PHI, KEEP})

# Non-empty is enforced only where a blank would break the harness or the comparison.
_REQUIRED_NON_EMPTY: tuple[str, ...] = ("image_id", "series_uid", "token_text")

# --- error codes -----------------------------------------------------------------------

FILE_EMPTY = "FILE_EMPTY"
FILE_NOT_UTF8 = "FILE_NOT_UTF8"
HEADER_BOM = "HEADER_BOM"
HEADER_MISSING_COLUMN = "HEADER_MISSING_COLUMN"
HEADER_EXTRA_COLUMN = "HEADER_EXTRA_COLUMN"
HEADER_DUPLICATE_COLUMN = "HEADER_DUPLICATE_COLUMN"
HEADER_ORDER = "HEADER_ORDER"
ROW_EMPTY = "ROW_EMPTY"
ROW_FIELD_COUNT = "ROW_FIELD_COUNT"
FIELD_EMPTY = "FIELD_EMPTY"
FRAME_IDX_NOT_INT = "FRAME_IDX_NOT_INT"
FRAME_IDX_NEGATIVE = "FRAME_IDX_NEGATIVE"
COORD_NOT_NUMERIC = "COORD_NOT_NUMERIC"
COORD_NOT_FINITE = "COORD_NOT_FINITE"
COORD_NEGATIVE = "COORD_NEGATIVE"
BOX_X_ORDER = "BOX_X_ORDER"
BOX_Y_ORDER = "BOX_Y_ORDER"
BOX_OUT_OF_BOUNDS = "BOX_OUT_OF_BOUNDS"
IMAGE_SIZE_UNKNOWN = "IMAGE_SIZE_UNKNOWN"
LABEL_INVALID = "LABEL_INVALID"

# Fixed explanations. This table is the ONLY source of human-readable text in a report,
# which is what makes a report PHI-free by construction (see module docstring).
_CODE_DETAIL: dict[str, str] = {
    FILE_EMPTY: "file has no header row",
    FILE_NOT_UTF8: "file is not valid UTF-8",
    HEADER_BOM: "header starts with a UTF-8 BOM (file was rewritten by another tool)",
    HEADER_MISSING_COLUMN: "required column is absent from the header",
    HEADER_EXTRA_COLUMN: "header has a column that is not in the frozen spec",
    HEADER_DUPLICATE_COLUMN: "column name appears more than once in the header",
    HEADER_ORDER: "header has the right columns in the wrong order",
    ROW_EMPTY: "blank line in the data section",
    ROW_FIELD_COUNT: "row does not have exactly one field per column",
    FIELD_EMPTY: "required field is empty",
    FRAME_IDX_NOT_INT: "frame_idx is not a canonical base-10 integer",
    FRAME_IDX_NEGATIVE: "frame_idx is negative",
    COORD_NOT_NUMERIC: "coordinate does not parse as a number",
    COORD_NOT_FINITE: "coordinate is NaN or infinite",
    COORD_NEGATIVE: "coordinate is negative",
    BOX_X_ORDER: "box violates x0 < x1",
    BOX_Y_ORDER: "box violates y0 < y1",
    BOX_OUT_OF_BOUNDS: "box extends past the image edge",
    IMAGE_SIZE_UNKNOWN: "image_id is absent from image_sizes, so bounds cannot be checked",
    LABEL_INVALID: "label is not exactly 'PHI' or 'KEEP' (case-sensitive)",
}


# --- report types ----------------------------------------------------------------------


@dataclass(frozen=True)
class GTError:
    """One violation. Carries NO field values — only a code, a row index, a column name.

    `row` is the 1-based DATA row number (the header is not row 1); it is `None` for
    file- and header-level violations.
    """

    code: str
    row: int | None = None
    column: str | None = None

    @property
    def detail(self) -> str:
        """Fixed explanation for this code. Never interpolates data."""
        return _CODE_DETAIL.get(self.code, "unspecified violation")


@dataclass(frozen=True)
class GTReport:
    """The outcome of validating one `gt.csv`. Safe to print, log, or paste back."""

    path: str
    n_rows: int
    n_images: int
    n_known_sizes: int
    errors: tuple[GTError, ...]

    @property
    def ok(self) -> bool:
        return not self.errors

    def counts_by_code(self) -> dict[str, int]:
        counts: dict[str, int] = {}
        for err in self.errors:
            counts[err.code] = counts.get(err.code, 0) + 1
        return dict(sorted(counts.items()))

    def summary(self, max_rows_listed: int = 10) -> str:
        """A PHI-free, human-readable report. Row indices and counts only."""
        lines = [
            f"gt.csv validation: {'PASS' if self.ok else 'FAIL'}",
            f"  file:              {self.path}",
            f"  data rows:         {self.n_rows}",
            f"  distinct image_ids:{self.n_images:>4}",
            f"  bounds check:      ON ({self.n_known_sizes} image sizes supplied)",
            f"  violations:        {len(self.errors)}",
        ]
        by_code: dict[str, list[GTError]] = {}
        for err in self.errors:
            by_code.setdefault(err.code, []).append(err)
        for code in sorted(by_code):
            group = by_code[code]
            cols = sorted({e.column for e in group if e.column is not None})
            rows = [e.row for e in group if e.row is not None]
            shown = ", ".join(str(r) for r in rows[:max_rows_listed])
            if len(rows) > max_rows_listed:
                shown += f", ... (+{len(rows) - max_rows_listed} more)"
            lines.append(f"    {code} x{len(group)} — {_CODE_DETAIL.get(code, '')}")
            if cols:
                lines.append(f"      columns: {', '.join(cols)}")
            if shown:
                lines.append(f"      rows: {shown}")
        return "\n".join(lines)


class GTValidationError(Exception):
    """Raised by `load_gt()` when the file violates the frozen spec.

    `str(err)` is the report summary — PHI-free like everything else here.
    """

    def __init__(self, report: GTReport) -> None:
        super().__init__(report.summary())
        self.report = report


# --- validation / loading ---------------------------------------------------------------


def validate_gt(path: str | Path, image_sizes: Mapping[str, tuple[int, int]]) -> GTReport:
    """Check `path` against the frozen spec and return every violation found.

    Collects rather than raises (decision 5): a human runs this once over the whole GT and
    wants the full list. Use `load_gt()` when a program needs the data.

    `image_sizes` maps `image_id -> (width, height)` in pixels — 10b's render manifest,
    narrowed. It is required: the in-bounds check is not skippable (decision 2). An
    `image_id` missing from it is reported as `IMAGE_SIZE_UNKNOWN`, never silently passed.

    Raises:
        FileNotFoundError: `path` does not exist. A missing file is not a schema violation,
            and an empty report would be indistinguishable from a valid header-only file.
    """
    report, _ = _read(path, image_sizes)
    return report


def load_gt(
    path: str | Path, image_sizes: Mapping[str, tuple[int, int]]
) -> dict[str, list[GTToken]]:
    """Validate `path`, then return `{image_id: [GTToken, ...]}` — `run_harness`'s shape.

    Rows keep their file order within each `image_id`. `token_text` is byte-identical to the
    CSV; `normalize()` is NOT applied (see module docstring).

    NOTE for the caller — blank controls are ABSENT, not empty. A confirmed-blank frame has
    zero rows in `gt.csv`, so its `image_id` is not a key of this dict. Iterate images with
    `gt.get(image_id, [])`, which is what `run_harness` does. The default belongs in the
    CALLER, where the image set is authoritative, and is deliberately not papered over HERE
    with a `defaultdict`, which would silently invent empty ground truth for a mistyped
    `image_id` — turning a typo into a free hallucination-floor pass.

    Raises:
        FileNotFoundError: `path` does not exist.
        GTValidationError: the file violates the frozen spec (any violation at all).
    """
    report, gt = _read(path, image_sizes)
    if not report.ok:
        raise GTValidationError(report)
    return gt


def _read(
    path: str | Path, image_sizes: Mapping[str, tuple[int, int]]
) -> tuple[GTReport, dict[str, list[GTToken]]]:
    """Single pass: validate and build. Returns the report plus whatever parsed cleanly."""
    p = Path(path)
    errors: list[GTError] = []
    gt: dict[str, list[GTToken]] = {}
    image_ids: set[str] = set()

    with p.open(newline="", encoding="utf-8") as fh:
        try:
            rows = list(csv.reader(fh))
        except UnicodeDecodeError:
            # Converted to a code rather than re-raised so no raw bytes reach the caller.
            return _report(p, 0, 0, image_sizes, [GTError(FILE_NOT_UTF8)]), {}

    if not rows:
        return _report(p, 0, 0, image_sizes, [GTError(FILE_EMPTY)]), {}

    header = list(rows[0])
    if header and header[0].startswith("\ufeff"):
        errors.append(GTError(HEADER_BOM))
        header[0] = header[0].lstrip("\ufeff")

    errors.extend(_check_header(header))

    # Rows are examined only when the header holds exactly the right column NAMES; order may
    # differ (that is its own violation, already recorded, and columns are read by name).
    # With a missing/extra/duplicate column there is no trustworthy mapping, so row-level
    # errors would be noise — the header is the thing to fix first.
    if sorted(header) != sorted(COLUMNS):
        return _report(p, len(rows) - 1, 0, image_sizes, errors), {}

    for i, raw in enumerate(rows[1:], start=1):
        if not raw:
            errors.append(GTError(ROW_EMPTY, row=i))
            continue
        if len(raw) != len(COLUMNS):
            errors.append(GTError(ROW_FIELD_COUNT, row=i))
            continue
        values = dict(zip(header, raw, strict=True))
        image_ids.add(values["image_id"])
        token, row_errors = _parse_row(i, values, image_sizes)
        errors.extend(row_errors)
        if token is not None:
            gt.setdefault(token.image_id, []).append(token)

    return _report(p, len(rows) - 1, len(image_ids), image_sizes, errors), gt


def _report(
    path: Path,
    n_rows: int,
    n_images: int,
    image_sizes: Mapping[str, tuple[int, int]],
    errors: list[GTError],
) -> GTReport:
    return GTReport(
        path=str(path),
        n_rows=max(n_rows, 0),
        n_images=n_images,
        n_known_sizes=len(image_sizes),
        errors=tuple(errors),
    )


def _check_header(header: list[str]) -> list[GTError]:
    """Exact ordered match against `COLUMNS`, with the failure modes reported separately."""
    errors: list[GTError] = []
    seen: set[str] = set()
    for name in header:
        if name in seen:
            errors.append(GTError(HEADER_DUPLICATE_COLUMN, column=name))
        seen.add(name)
    for name in COLUMNS:
        if name not in seen:
            errors.append(GTError(HEADER_MISSING_COLUMN, column=name))
    for name in sorted(seen - set(COLUMNS)):
        errors.append(GTError(HEADER_EXTRA_COLUMN, column=name))
    if not errors and tuple(header) != COLUMNS:
        errors.append(GTError(HEADER_ORDER))
    return errors


def _parse_row(
    row: int, values: dict[str, str], image_sizes: Mapping[str, tuple[int, int]]
) -> tuple[GTToken | None, list[GTError]]:
    """Validate one data row; return its `GTToken` (only if clean) and its violations."""
    errors: list[GTError] = []

    for name in _REQUIRED_NON_EMPTY:
        if not values[name]:
            errors.append(GTError(FIELD_EMPTY, row=row, column=name))

    frame_idx = _parse_frame_idx(row, values["frame_idx"], errors)
    coords = _parse_coords(row, values, errors)

    if coords is not None:
        x0, y0, x1, y1 = coords
        if x0 >= x1:
            errors.append(GTError(BOX_X_ORDER, row=row, column="x1"))
        if y0 >= y1:
            errors.append(GTError(BOX_Y_ORDER, row=row, column="y1"))
        size = image_sizes.get(values["image_id"])
        if size is None:
            errors.append(GTError(IMAGE_SIZE_UNKNOWN, row=row, column="image_id"))
        else:
            # Top-left origin, y down (D-2.2). A box may TOUCH the far edge, so the bound
            # is <= w / <= h, not < w / < h.
            width, height = size
            if x1 > width:
                errors.append(GTError(BOX_OUT_OF_BOUNDS, row=row, column="x1"))
            if y1 > height:
                errors.append(GTError(BOX_OUT_OF_BOUNDS, row=row, column="y1"))

    label = values["label"]
    if label not in ALLOWED_LABELS:
        errors.append(GTError(LABEL_INVALID, row=row, column="label"))

    if errors or frame_idx is None or coords is None:
        return None, errors
    return (
        GTToken(
            image_id=values["image_id"],
            series_uid=values["series_uid"],
            modality=values["modality"],
            vendor=values["vendor"],
            stratum=values["stratum"],
            frame_idx=frame_idx,
            token_text=values["token_text"],  # RAW — no strip, no normalize()
            bbox=coords,
            label=label,
        ),
        errors,
    )


def _parse_frame_idx(row: int, raw: str, errors: list[GTError]) -> int | None:
    try:
        value = int(raw, 10)
    except ValueError:
        errors.append(GTError(FRAME_IDX_NOT_INT, row=row, column="frame_idx"))
        return None
    if str(value) != raw:
        # "03", "+3", " 3" all parse but are not the one canonical spelling. A frozen,
        # hashed artifact gets exactly one representation per value.
        errors.append(GTError(FRAME_IDX_NOT_INT, row=row, column="frame_idx"))
        return None
    if value < 0:
        errors.append(GTError(FRAME_IDX_NEGATIVE, row=row, column="frame_idx"))
        return None
    return value


def _parse_coords(
    row: int, values: dict[str, str], errors: list[GTError]
) -> tuple[float, float, float, float] | None:
    parsed: list[float] = []
    clean = True
    for name in BBOX_COLUMNS:
        raw = values[name]
        try:
            value = float(raw)
        except ValueError:
            errors.append(GTError(COORD_NOT_NUMERIC, row=row, column=name))
            clean = False
            continue
        if not math.isfinite(value):
            # NaN/inf parse fine and then poison IoU silently — reject them here.
            errors.append(GTError(COORD_NOT_FINITE, row=row, column=name))
            clean = False
            continue
        if value < 0:
            errors.append(GTError(COORD_NEGATIVE, row=row, column=name))
            clean = False
            continue
        parsed.append(value)
    if not clean:
        return None
    return (parsed[0], parsed[1], parsed[2], parsed[3])
